gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
#    return_expiration: true
#    single_use: true
#    ttl: 1296000
#    cookie:
#        enabled: true
#        http_only: true
#        path: /
#
#when@prod:
#    gesdinet_jwt_refresh_token:
#        cookie:
#            domain: "%env(REFRESH_TOKEN_COOKIE_DOMAIN)%"
#            same_site: strict
#            secure: true
#
#when@dev:
#    gesdinet_jwt_refresh_token:
#        cookie:
#            same_site: lax
#            secure: false
